spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/user-service/**
      discovery:
        locator:
          enabled: true
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/