spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
