spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/