server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**  # Match requests for /auth/*
          filters:
            - RewritePath=/auth/(?<segment>.*), /$\\{segment}  # Remove /auth prefix
        - id: common-service
          uri: lb://common-service
          predicates:
            - Path=/common/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true