spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**  # Match requests starting with /auth/*
          filters:
            - StripPrefix=0  # Do not remove any prefix
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true