spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/auth/**  # Match requests starting with /user-service/auth/*
          filters:
            - StripPrefix=1  # Remove the /user-service prefix
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true