spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: useradmin
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8082
