FROM eclipse-temurin:17-jdk-alpine

# Add curl so Docker healthcheck works
RUN apk add --no-cache curl

VOLUME /tmp
COPY target/discovery-service-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
