spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8082
jwt:
  secret: mySuperSecretJwtKey12345  # Should be at least 256 bits (32+ chars)
  expiration: 3600000  # 1 hour in milliseconds
