spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://config-server:8888
  #datasource:
  #  url: jdbc:mysql://mysql:3306/userdb
  #  username: useradmin
  #  password: secret
  #  driver-class-name: com.mysql.cj.jdbc.Driver

  #jpa:
  #  hibernate:
  #    ddl-auto: update
  #  show-sql: true
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

#server:
#  port: 8082

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.cloud.config.client: DEBUG
