spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: local  # Activate local profile when running from IDE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
