spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8082