spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8082

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.cloud.config.client: DEBUG
