server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ponir-saha/notification-system.git
          clone-on-start: true
          default-label: main
          search-paths: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
